language: java
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
    - jq
before_install:
  - export TZ=America/Chicago
after_success:
  - ./dev/coverage.sh codacy codecov
notifications:
  email:
    recipients:
      - pejman@ghorbanzade.com
    on_success: change
    on_failure: always
