language: java
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
    - jq
after_success:
  - ./tools/coverage.sh codacy codecov
notifications:
  email:
    recipients:
      - pejman@ghorbanzade.com
    on_success: change
    on_failure: always
